version: 1.0.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: Any CPU
test: off
branches:
  only:
  - master
  - /feature.*/
environment:
  NuGetApiKey:
    secure: FkbOZI29wVSKdzHuFOq9tY8cq05Sy6vFKwvqYnUhDVamagkTUrjNJElPPoACP8Ov
build_script:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
- ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
- ps: cp "Microsoft.NET.Sdk\targets" -Destination "C:\Program Files\dotnet\sdk\3.0.100-alpha1-009706\Sdks\Microsoft.NET.Sdk\targets"
- ps: .\build.ps1 --settings_skipverification=true
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\msbuild.binlog
- path: artifacts\**\site.zip
- path: artifacts\*.xml
- path: artifacts\*.html
on_failure:
- appveyor PushArtifact artifacts\msbuild.binlog
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
