version: 0.5.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 2
test: off
branches:
  only:
  - master
# Workaround for http://help.appveyor.com/discussions/problems/7097-builds-timing-out
hosts:
  api.nuget.org: 93.184.221.200
environment:
  NuGetApiKey:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA
build_script:
- ps: .\build.ps1
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\site.zip
- path: artifacts\*.xml
- path: artifacts\*.html
# Test with Blackduck CoPilot
on_success:
- nuget install Hub-Nuget -Version 1.1.1
- Hub-NuGet.1.1.1\tools\buildBom.exe --hub_deploy_bdio=false --hub_create_merged_bdio=true
- curl -s https://copilot.blackducksoftware.com/batch/appveyor > appveyor.bat
- appveyor
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
